# TODO: test condor
language: python
python: 2.7
env:
  - TOX_ENV=py27-lint
  - TOX_ENV=py34-lint
  - TOX_ENV=py27-lint-readme
  - TOX_ENV=lint-docs
  - TOX_ENV=py26 SETUP=true
  - TOX_ENV=py27 SETUP=true
  - TOX_ENV=py34 SETUP=true

install:
  - pip install tox
  - if [ "$SETUP" == "true" ]; then .travis/setup_tests.sh; fi

script: export PULSAR_TEST_KEY=test_data/testkey; export TEST_WEBAPP_POST_SHUTDOWN_SLEEP=1; . local_env.sh; tox -e $TOX_ENV

after_success:
  - coveralls
